# Assignment 2 - CT5120

### Instructions:
- Complete all the tasks below and upload your submission as a Python notebook on Blackboard with the filename “`StudentID_Lastname.ipynb`” before **23:59** on **November 25, 2022**.
- This is an individual assignment, you **must not** work with other students to complete this assessment.
- The assignment is worth $50$ marks and constitutes 19% of the final grade. The breakdown of the marking scheme for each task is as follows:

| Task | Marks for write-up | Marks for code | Total Marks |
| :--- | :----------------- | :------------- | :---------- |
| 1    |                  5 |              5 |          10 |
| 2    |                  - |             10 |          10 |
| 3    |                  5 |              5 |          10 |
| 4    |                  5 |              5 |          10 |
| 5    |                  5 |              5 |          10 |



---

This assignment involves tasks for feature engineering, training and evaluating a classifier for suggestion detection. You will work with the data from SemEval-2019 Task 9 subtask A to classify whether a piece of text contains a suggestion or not. 


Download train.csv, test_seen.csv and test_unseen.csv from the [Github](https://github.com/sharduls007/Assignment_2_CT5120) or uncomment the code cell below to get the data as a comma-separated values (CSV) file. The CSV file contains a header row followed by 5,440 rows in train.csv and 1,360 rows in test_seen.csv spread across 3 columns of data. Each row of data contains a unique id, a piece of text and a label assigned by an annotator. A label of $1$ indicates that the given text contains a suggestion while a label of $0$ indicates that the text does not contain a suggestion.

You can find more details about the dataset in Sections 1, 2, 3 and 4 of [SemEval-2019 Task 9: Suggestion Mining from Online Reviews and Forums
](https://aclanthology.org/S19-2151/).

We will be using test_seen.csv for benchmarking our model, hence it has label. On the other hand, test_unseen is used for [Kaggle](https://www.kaggle.com/competitions/nlp2022ct5120suggestionmining/overview) competition.


In [1]:
# !curl "https://raw.githubusercontent.com/sharduls007/Assignment_2_CT5120/master/train.csv" > train.csv
# !curl "https://raw.githubusercontent.com/sharduls007/Assignment_2_CT5120/master/test_seen.csv" > test.csv
# !curl "https://raw.githubusercontent.com/sharduls007/Assignment_2_CT5120/master/test_unseen.csv" > test_unseen.csv

In [9]:
import numpy as np
import pandas as pd

# Read the CSV file.
train_df = pd.read_csv('train.csv', 
                 names=['id', 'text', 'label'], header=0)

test_df = pd.read_csv('test.csv', 
                 names=['id', 'text', 'label'], header=0)

# Store the data as a list of tuples where the first item is the text
# and the second item is the label.
train_texts, train_labels = train_df["text"].to_list(), train_df["label"].to_list() 
test_texts, test_labels = test_df["text"].to_list(), test_df["label"].to_list() 

# Check that training set and test set are of the right size.
assert len(test_texts) == len(test_labels) == 1360
assert len(train_texts) == len(train_labels) == 5440

---

## Task 1: Data Pre-processing (10 Marks)

Explain at least 3 steps that you will perform to preprocess the texts before training a classifier.



Edit this cell to write your answer below the line in no more than 300 words.

---

> Check if there is any missing value.

> Remove the stop words. Remove function words which are less imformative about the text. We can safely remove them without lossing any valuable information.

> Remove the punctuations.

> Lowercase the text. It is one of the most common preprocessing steps where the text is converted into the same case preferably lower case.

> Stemming. Stemming is a simplified analysis of word structure by removing endings/beginnings of words - leaving a common stem. There are many algorithms to perform stemming, with PorterStemmer being one of the most widely used. Run the following cell to see the output from the stemmer for the sentence defined above.

> Lemmatization. Lemmatisation is the linguistic analysis of word structure by a transformation of morphologically related words to a common lemma.
Lemmatization is more complex than stemming as it depends on correctly identifying part of speech and meaning of a word in a sentence. Run the following cell to see the output from the WordNetLemmatizer.

---

In the code cell below, write an implementation of the steps you defined above. You are free to use a library such as `nltk` or `sklearn` for this task.

In [10]:
from nltk.corpus import stopwords
from string import punctuation
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

def data_preprocessing(df):
    
    # Check if there is any missing value.
    print(f"Are there missing value? {df.isnull().any()}")
    
    # remove stopwords
    stops = set(stopwords.words('english')) # store the english stop words
    df['preprocess'] = df['text'].apply(lambda x: ' '.join([w for w in x.split() if w not in (stops)]))
    
    # remove puncuations
    punct = punctuation + '—«»–„“‘’'
    df['preprocess'] = df['preprocess'].apply(lambda x: ' '.join([w.strip(punct) for w in x.split()]))

    # lowercase the text
    df['preprocess'] = df['preprocess'].apply(lambda x: ' '.join([w.lower() for w in x.split()]))
    
    # stemming
    stemmer = PorterStemmer()
    df["preprocess"] = df["preprocess"].apply(lambda x: ' '.join([stemmer.stem(w) for w in x.split()]))

    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    df["preprocess"] = df["preprocess"].apply(lambda x: ' '.join([lemmatizer.lemmatize(w) for w in x.split()]))
    
    return df

In [11]:
train_preprocess_df = data_preprocessing(train_df)
test_preprocess_df = data_preprocessing(test_df)

Are there missing value? id       False
text     False
label    False
dtype: bool
Are there missing value? id       False
text     False
label    False
dtype: bool


In [12]:
train_preprocess_df.head()

id                                               text  label  \
0  train_0  "One would hope if I search for a word in the ...      0   
1  train_1     "I would be beyond excited to get a response."      0   
2  train_2  "Just like the user can select apps that are a...      1   
3  train_3  "Once you create a CoreIndependentInputSource ...      0   
4  train_4  "I Have problems with Contact class on Windows...      0   

                                          preprocess  
0  one would hope i search word titl app would sh...  
1                   i would beyond excit get respons  
2  just like user select app allow run background...  
3  onc creat coreindependentinputsourc touch visu...  
4  i have problem contact class window 8.1 window...

In [13]:
test_preprocess_df.head()

id                                               text  label  \
0  dev_0  "I understand why you might do this for the FR...      1   
1  dev_1  "This is a significant bug and kind of hard to...      0   
2  dev_2  "This leads the user to have to type AGAIN the...      0   
3  dev_3  "Needless to say, disappointed, it appears I c...      0   
4  dev_4  "Implementing the Auto-Upload feature in a Sil...      0   

                                          preprocess  
0  i understand might free version feedli implor ...  
1              thi signific bug kind hard believ fix  
2            thi lead user type again whole descript  
3  needle say disappoint appear i cannot develop ...  
4  implement auto-upload featur silverlight 8.1 a...

---

## Task 2: Feature Engineering (I) - TF-IDF as features (10 Marks)

In the lectures we have seen that raw counts of words and `tf-idf` scores can be useful features for a classification task. Complete the following code cell to create a suggestion detector which uses `tf-idf` scores as features for a Naïve Bayes classifier.

After applying your preprocessing steps, use the training data to train the classifier and make predictions on the test set. You **must not** use the test set for training.

If everything is implemented correctly, then you should see a single floating point value between 0 and 1 at the end which denotes the accuracy of the classifier.

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.naive_bayes import GaussianNB

# Calculate tf-idf scores for the words in the training set.
# ... your code goes here

count_vectorizer = CountVectorizer()
train_X = train_df["preprocess"]
X_train_counts = count_vectorizer.fit_transform(x for x in train_X)

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)


# Train a Naïve Bayes classifier using the tf-idf scores for words as features.
# ... your code goes here
NB_classifier_tfidf = GaussianNB()
NB_classifier_tfidf.fit(X_train_tfidf.toarray(), train_labels)


# Predict on the test set.
predictions = []    # save your predictions on the test set into this list

# ... your code goes here
# generate the features for the test set
test_X = test_df["preprocess"]
X_test_counts = count_vectorizer.transform(x for x in test_X)
X_test_tfidf = tfidf_transformer.transform(X_test_counts)

predictions = NB_classifier_tfidf.predict(X_test_tfidf.toarray())


#################### DO NOT EDIT BELOW THIS LINE #################


#################### DO NOT EDIT BELOW THIS LINE #################

def accuracy(labels, predictions):
    '''
    Calculate the accuracy score for a given set of predictions and labels.

    Args:
    labels (list): A list containing gold standard labels annotated as `0` and `1`.
    predictions (list): A list containing predictions annotated as `0` and `1`.

    Returns:
    float: A floating point value to score the predictions against the labels.
    '''

    assert len(labels) == len(predictions)

    correct = 0
    for label, prediction in zip(labels, predictions):
        if label == prediction:
            correct += 1 

    score = correct / len(labels)
    return score

# Calculate accuracy score for the classifier using tf-idf features.
accuracy(test_labels, predictions)

0.5279411764705882

---

## Task 3: Evaluation Metrics (10 marks)

Why is accuracy not the best measure for evaluating a classifier? Describe an evaluation metric which might work better than accuracy for a classification task such as suggestion detection.

Edit this cell to write your answer below the line in no more than 150 words.

---

> We formalise the accuracy as $Accuracy=\frac{correct}{len(labels)}$. It will fail when the dataset consists of unbalanced classes. For instance, in one dataset, if we have 90% data belong to class A and 10% data belong to class B. Even if the hypothesis fails to predict the data belongs to class B, the accuracy will be high as it can predict the data belong to class A. Therefore, accuracy does not the best measure for evaluating a classifier. 

> Confusion matrix F1 score

---

In the code cell below, write an implementation of the evaluation metric you defined above. Please write your own implementation from scratch.

In [16]:
def evaluate(labels, predictions):
    '''
    Calculate an evaluation score other than accuracy for a given set of predictions and labels.

    Args:
    labels (list): A list containing gold standard labels annotated as `0` and `1`.
    predictions (list): A list containing predictions annotated as `0` and `1`.

    Returns:
    float: A floating point value to score the predictions against the labels.
    '''

    # check that labels and predictions are of same length
    assert len(labels) == len(predictions)

    score = 0.0

    #################### EDIT BELOW THIS LINE #########################

    # your code goes here
    num_classes = len(np.unique(labels)) # Number of classes 
    c_matrix = np.zeros((num_classes, num_classes))

    for i in range(len(labels)):
        c_matrix[labels[i]][predictions[i]] += 1

    score = 2*c_matrix[0][0] / (2*c_matrix[0][0] + c_matrix[1][0] + c_matrix[0][1]) # F1 score
    
    #################### EDIT ABOVE THIS LINE #########################

    return score

# Calculate evaluation score based on the metric of your choice
# for the classifier trained in Task 2 using tf-idf features.
evaluate(test_labels, predictions)

0.6085365853658536

---

## Task 4: Feature Engineering (II) - Other features (10 Marks)

Describe features other than those defined in Task 2 which might improve the performance of your suggestion detector. If these features require any additional pre-processing steps, then define those steps as well.


Edit this cell to write your answer below the line in no more than 500 words.

---

> Delete this line and your write answer here

> Using Word Embeddings as Features

> GloVe is very similar to word2vec, but it starts off with buildings a co-occurence matrix, which makes it a hybrid model.
GloVe is based on ratios of probabilities from the word-word co-occurrence matrix, combining the intuitions of count-based models while also capturing the linear structures used by methods like word2vec (Pennington et al. 2014)
Here and here are good explanations of the differences between word2vec and GloVe in more detail.
The GloVe embedding model was proposed by the Stanford NLP group in 2014. Here is the article and the website for the project.

> Tokenization. Tokenization is the process of dividing a text into smaller units i.e. tokens.
nltk provides a word_tokenize function to tokenize a sentence in a given language.

> mean pooling

---

In the code cell below, write an implementation of the features (and any additional pre-preprocessing steps) you defined above. You are free to use a library such as `nltk` or `sklearn` for this task.

After creating your features, use the training data to train a Naïve Bayes classifier and use the test set to evaluate its performance using the metric defined in Task 3. You **must not** use the test set for training.

To make sure that your code doesn't take too long to run or use too much memory, you can consider a time limit of 3 minutes and a memory limit of 12GB for this task.

In [33]:
# Create your features.
# ... your code goes here
import gensim.downloader as api
glove = api.load('glove-wiki-gigaword-300')

# Tokenization
train_tokens = [word_tokenize(sent) for sent in train_df["preprocess"]]
test_tokens = [word_tokenize(sent) for sent in test_df["preprocess"]]

def word_embedding_mean_pooling(tokens): # extract the word embeddings for each word in the input
    all_pooled_vecs = []
    
    oov = np.random.rand(1,300) # random vector to represent out-of-vocab

    for toks in train_tokens:
        text_vecs = []

        for tok in toks:
            if tok in glove:
                mean_pool = np.mean(np.vstack(glove[tok]), axis=0)
                all_pooled_vecs.append(mean_pool)
            else:
                mean_pool = np.mean(np.vstack(oov), axis=0)
                all_pooled_vecs.append(mean_pool)

    #df["embeddings"] = all_pooled_vecs
    
    return all_pooled_vecs


# Train a Naïve Bayes classifier using the features you defined.
# ... your code goes here
# NB_classifier_emb = GaussianNB()
# NB_classifier_emb.fit(word_embedding_mean_pooling(train_tokens), train_labels)
# preds = NB_classifier_emb.predict(test_tokens)

# Evaluate on the test set.
# ... your code goes here

In [35]:
all_pooled_vecs = word_embedding_mean_pooling(train_tokens)

In [38]:
all_pooled_vecs

[array([0.00103563], dtype=float32),
 array([0.0094115], dtype=float32),
 array([-0.0061282], dtype=float32),
 array([-0.00906112], dtype=float32),
 array([-0.01427851], dtype=float32),
 array([-0.00206503], dtype=float32),
 array([0.49270497, 0.14408031, 0.06355362, 0.76444143, 0.99433624,
        0.08576202, 0.19322548, 0.44464105, 0.68433327, 0.67702083,
        0.81132807, 0.55400211, 0.55940804, 0.78777252, 0.81619395,
        0.83072325, 0.27954726, 0.93347045, 0.73424948, 0.36948924,
        0.07481283, 0.41160118, 0.44019642, 0.76053286, 0.1599249 ,
        0.19094049, 0.2461539 , 0.35416748, 0.24702819, 0.54303872,
        0.43933189, 0.23498492, 0.055833  , 0.71704065, 0.15127332,
        0.80205185, 0.29082293, 0.84125331, 0.57979348, 0.59042245,
        0.12506395, 0.60229833, 0.49734998, 0.66162932, 0.21540452,
        0.51309505, 0.58152686, 0.19464293, 0.0740517 , 0.28734737,
        0.50617724, 0.31919438, 0.81037782, 0.31644568, 0.25544238,
        0.51084955, 0.605347

In [39]:
train_tokens

[['one',
  'would',
  'hope',
  'i',
  'search',
  'word',
  'titl',
  'app',
  'would',
  'show',
  'search'],
 ['i', 'would', 'beyond', 'excit', 'get', 'respons'],
 ['just',
  'like',
  'user',
  'select',
  'app',
  'allow',
  'run',
  'background',
  'would',
  'great',
  'could',
  'select',
  'app',
  'allow',
  'chang',
  'phone',
  'set'],
 ['onc',
  'creat',
  'coreindependentinputsourc',
  'touch',
  'visual',
  'feedback',
  'visibl',
  'again'],
 ['i',
  'have',
  'problem',
  'contact',
  'class',
  'window',
  '8.1',
  'windowsphon',
  '8.1',
  'with',
  'code',
  'var',
  'p',
  'new',
  'windows.applicationmodel.contacts.contactpick',
  'p.desiredfieldswithcontactfieldtype.add',
  '(',
  'windows.applicationmodel.contacts.contactfieldtype.email',
  'ilist',
  '<',
  'windows.applicationmodel.contacts.contact',
  'contact',
  'await',
  'p.pickcontactsasync',
  'contacts.count',
  '0',
  'foreach',
  'windows.applicationmodel.contacts.contact',
  'c',
  'contact',
  'awa

---

## Task 5: Kaggle Competition (10 marks)

Head over to https://www.kaggle.com/t/1f90b74da0b7484da9647638e22d1068  
Use above classifier to predict the label for test_unseen.csv from competition page and upload the results to the leaderboard. The current baseline score is 0.36823. Make an improvement above the baseline. Please note that the evaluation metric for the competition is the f-score.

Read competition page for more details.



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Preparing submission for Kaggle
StudentID = "StudentID_Lastname" # Please add your student id and lastname
test_unseen = pd.read_csv("test_unseen.csv", names=['id', 'text'], header=0)

# Here Id is unique identifier assigned to each test sample ranging from test_0 till test_1699
# Expected is a list of prediction made by your classifier
sub = {"Id": [f"test_{i}" for i in range(len(test_unseen))],
       "Expected": []}

sub_df = pd.DataFrame(sub)
# The code below will generate a StudentID.csv on your drive on the left hand side in the explorer
# Please upload the file as a submission on the competition page
# You can index your submission StudentID_Lastname_index.csv, where index is your number of submission
sub_df.to_csv(f"{StudentID}.csv", sep=",", header=1, index=None)

Mention the approach that you have chosen briefly, and what is the mean average f-score that you have achieved? Did it improve above the chosen baseline model (0.36823)? Why or why not?

Edit this cell to write your answer below the line in no more than 500 words.

---

> Delete this line and your write answer here

---